/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package automotive.laboratory;

import javax.swing.table.DefaultTableModel;

/**
 *
 * @author bajal
 */
public class Main extends javax.swing.JFrame {

    /**
     * Creates new form Main
     */
    public Main() {
        initComponents();
    }
    
    DefaultTableModel model = new DefaultTableModel();
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel4 = new javax.swing.JPanel();
        jCheckBox1 = new javax.swing.JCheckBox();
        jCheckBox2 = new javax.swing.JCheckBox();
        jCheckBox3 = new javax.swing.JCheckBox();
        jCheckBox4 = new javax.swing.JCheckBox();
        jCheckBox5 = new javax.swing.JCheckBox();
        jCheckBox6 = new javax.swing.JCheckBox();
        jCheckBox7 = new javax.swing.JCheckBox();
        jCheckBox8 = new javax.swing.JCheckBox();
        jCheckBox9 = new javax.swing.JCheckBox();
        jCheckBox10 = new javax.swing.JCheckBox();
        jCheckBox11 = new javax.swing.JCheckBox();
        jCheckBox12 = new javax.swing.JCheckBox();
        jCheckBox13 = new javax.swing.JCheckBox();
        jCheckBox14 = new javax.swing.JCheckBox();
        jCheckBox15 = new javax.swing.JCheckBox();
        jCheckBox16 = new javax.swing.JCheckBox();
        jSpinner1 = new javax.swing.JSpinner();
        jSpinner2 = new javax.swing.JSpinner();
        jSpinner3 = new javax.swing.JSpinner();
        jSpinner4 = new javax.swing.JSpinner();
        jSpinner5 = new javax.swing.JSpinner();
        jSpinner6 = new javax.swing.JSpinner();
        jSpinner7 = new javax.swing.JSpinner();
        jSpinner8 = new javax.swing.JSpinner();
        jSpinner9 = new javax.swing.JSpinner();
        jSpinner10 = new javax.swing.JSpinner();
        jSpinner11 = new javax.swing.JSpinner();
        jSpinner12 = new javax.swing.JSpinner();
        jSpinner13 = new javax.swing.JSpinner();
        jSpinner14 = new javax.swing.JSpinner();
        jSpinner15 = new javax.swing.JSpinner();
        jSpinner16 = new javax.swing.JSpinner();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 0, 120));

        jLabel1.setFont(new java.awt.Font("Nunito Sans", 1, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 200, 0));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("<html><center>Automotive Parts<br><center>Inventory System</center></html>");

        jTabbedPane1.setBackground(new java.awt.Color(0, 0, 120));
        jTabbedPane1.setFont(new java.awt.Font("Nunito Sans", 1, 18)); // NOI18N

        jPanel4.setBackground(new java.awt.Color(0, 0, 120));

        jCheckBox1.setBackground(new java.awt.Color(0, 0, 120));
        jCheckBox1.setFont(new java.awt.Font("Nunito Sans", 1, 14)); // NOI18N
        jCheckBox1.setForeground(new java.awt.Color(255, 200, 0));
        jCheckBox1.setText("Windshield Wiper");

        jCheckBox2.setBackground(new java.awt.Color(0, 0, 120));
        jCheckBox2.setFont(new java.awt.Font("Nunito Sans", 1, 14)); // NOI18N
        jCheckBox2.setForeground(new java.awt.Color(255, 200, 0));
        jCheckBox2.setText("Steering Wheel");

        jCheckBox3.setBackground(new java.awt.Color(0, 0, 120));
        jCheckBox3.setFont(new java.awt.Font("Nunito Sans", 1, 14)); // NOI18N
        jCheckBox3.setForeground(new java.awt.Color(255, 200, 0));
        jCheckBox3.setText("Windshield Washer");

        jCheckBox4.setBackground(new java.awt.Color(0, 0, 120));
        jCheckBox4.setFont(new java.awt.Font("Nunito Sans", 1, 14)); // NOI18N
        jCheckBox4.setForeground(new java.awt.Color(255, 200, 0));
        jCheckBox4.setText("Air Filter");

        jCheckBox5.setBackground(new java.awt.Color(0, 0, 120));
        jCheckBox5.setFont(new java.awt.Font("Nunito Sans", 1, 14)); // NOI18N
        jCheckBox5.setForeground(new java.awt.Color(255, 200, 0));
        jCheckBox5.setText("Battery");

        jCheckBox6.setBackground(new java.awt.Color(0, 0, 120));
        jCheckBox6.setFont(new java.awt.Font("Nunito Sans", 1, 14)); // NOI18N
        jCheckBox6.setForeground(new java.awt.Color(255, 200, 0));
        jCheckBox6.setText("Distributor");

        jCheckBox7.setBackground(new java.awt.Color(0, 0, 120));
        jCheckBox7.setFont(new java.awt.Font("Nunito Sans", 1, 14)); // NOI18N
        jCheckBox7.setForeground(new java.awt.Color(255, 200, 0));
        jCheckBox7.setText("Radiator");

        jCheckBox8.setBackground(new java.awt.Color(0, 0, 120));
        jCheckBox8.setFont(new java.awt.Font("Nunito Sans", 1, 14)); // NOI18N
        jCheckBox8.setForeground(new java.awt.Color(255, 200, 0));
        jCheckBox8.setText("Alternator");

        jCheckBox9.setBackground(new java.awt.Color(0, 0, 120));
        jCheckBox9.setFont(new java.awt.Font("Nunito Sans", 1, 14)); // NOI18N
        jCheckBox9.setForeground(new java.awt.Color(255, 200, 0));
        jCheckBox9.setText("Oil Filter");

        jCheckBox10.setBackground(new java.awt.Color(0, 0, 120));
        jCheckBox10.setFont(new java.awt.Font("Nunito Sans", 1, 14)); // NOI18N
        jCheckBox10.setForeground(new java.awt.Color(255, 200, 0));
        jCheckBox10.setText("Disk Brake");

        jCheckBox11.setBackground(new java.awt.Color(0, 0, 120));
        jCheckBox11.setFont(new java.awt.Font("Nunito Sans", 1, 14)); // NOI18N
        jCheckBox11.setForeground(new java.awt.Color(255, 200, 0));
        jCheckBox11.setText("Transmission");

        jCheckBox12.setBackground(new java.awt.Color(0, 0, 120));
        jCheckBox12.setFont(new java.awt.Font("Nunito Sans", 1, 14)); // NOI18N
        jCheckBox12.setForeground(new java.awt.Color(255, 200, 0));
        jCheckBox12.setText("Muffler");

        jCheckBox13.setBackground(new java.awt.Color(0, 0, 120));
        jCheckBox13.setFont(new java.awt.Font("Nunito Sans", 1, 14)); // NOI18N
        jCheckBox13.setForeground(new java.awt.Color(255, 200, 0));
        jCheckBox13.setText("Line Shaft");

        jCheckBox14.setBackground(new java.awt.Color(0, 0, 120));
        jCheckBox14.setFont(new java.awt.Font("Nunito Sans", 1, 14)); // NOI18N
        jCheckBox14.setForeground(new java.awt.Color(255, 200, 0));
        jCheckBox14.setText("Wheel");

        jCheckBox15.setBackground(new java.awt.Color(0, 0, 120));
        jCheckBox15.setFont(new java.awt.Font("Nunito Sans", 1, 14)); // NOI18N
        jCheckBox15.setForeground(new java.awt.Color(255, 200, 0));
        jCheckBox15.setText("Tail Light");

        jCheckBox16.setBackground(new java.awt.Color(0, 0, 120));
        jCheckBox16.setFont(new java.awt.Font("Nunito Sans", 1, 14)); // NOI18N
        jCheckBox16.setForeground(new java.awt.Color(255, 200, 0));
        jCheckBox16.setText("Trunk Shield");

        jSpinner1.setFont(new java.awt.Font("Nunito Sans", 0, 14)); // NOI18N

        jSpinner2.setFont(new java.awt.Font("Nunito Sans", 0, 14)); // NOI18N

        jSpinner3.setFont(new java.awt.Font("Nunito Sans", 0, 14)); // NOI18N

        jSpinner4.setFont(new java.awt.Font("Nunito Sans", 0, 14)); // NOI18N

        jSpinner5.setFont(new java.awt.Font("Nunito Sans", 0, 14)); // NOI18N

        jSpinner6.setFont(new java.awt.Font("Nunito Sans", 0, 14)); // NOI18N

        jSpinner7.setFont(new java.awt.Font("Nunito Sans", 0, 14)); // NOI18N

        jSpinner8.setFont(new java.awt.Font("Nunito Sans", 0, 14)); // NOI18N

        jSpinner9.setFont(new java.awt.Font("Nunito Sans", 0, 14)); // NOI18N

        jSpinner10.setFont(new java.awt.Font("Nunito Sans", 0, 14)); // NOI18N

        jSpinner11.setFont(new java.awt.Font("Nunito Sans", 0, 14)); // NOI18N

        jSpinner12.setFont(new java.awt.Font("Nunito Sans", 0, 14)); // NOI18N

        jSpinner13.setFont(new java.awt.Font("Nunito Sans", 0, 14)); // NOI18N

        jSpinner14.setFont(new java.awt.Font("Nunito Sans", 0, 14)); // NOI18N

        jSpinner15.setFont(new java.awt.Font("Nunito Sans", 0, 14)); // NOI18N

        jSpinner16.setFont(new java.awt.Font("Nunito Sans", 0, 14)); // NOI18N

        jButton1.setBackground(new java.awt.Color(0, 0, 120));
        jButton1.setFont(new java.awt.Font("Nunito Sans", 1, 18)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 200, 0));
        jButton1.setText("ADD");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setBackground(new java.awt.Color(0, 0, 120));
        jButton2.setFont(new java.awt.Font("Nunito Sans", 1, 18)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 200, 0));
        jButton2.setText("PRINT");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jCheckBox4, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jCheckBox5, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jCheckBox6, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jCheckBox3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jCheckBox7, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jCheckBox8, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jCheckBox2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jCheckBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jSpinner1, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jSpinner2, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jSpinner4, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jSpinner3, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jSpinner6, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jSpinner5, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jSpinner8, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jSpinner7, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jCheckBox13, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jCheckBox11, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jCheckBox12, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jCheckBox10, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jCheckBox9, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jCheckBox16, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jCheckBox15, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jCheckBox14, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jSpinner9, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jSpinner10, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jSpinner12, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jSpinner11, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jSpinner14, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jSpinner13, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jSpinner16, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jSpinner15, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(55, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(189, 189, 189)
                        .addComponent(jCheckBox14)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jCheckBox15))
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(jPanel4Layout.createSequentialGroup()
                            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jSpinner9, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jCheckBox9))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jSpinner10, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jCheckBox10))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jSpinner12, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jCheckBox11))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jSpinner11, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jCheckBox12))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jSpinner14, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jCheckBox13))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jSpinner13, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(5, 5, 5)
                            .addComponent(jSpinner16, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jSpinner15, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jCheckBox16)))
                        .addGroup(jPanel4Layout.createSequentialGroup()
                            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jCheckBox1)
                                .addComponent(jSpinner1, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jCheckBox2)
                                .addComponent(jSpinner2, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel4Layout.createSequentialGroup()
                                    .addComponent(jCheckBox3)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(jCheckBox4))
                                .addGroup(jPanel4Layout.createSequentialGroup()
                                    .addComponent(jSpinner4, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jSpinner3, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel4Layout.createSequentialGroup()
                                    .addComponent(jCheckBox5)
                                    .addGap(3, 3, 3)
                                    .addComponent(jCheckBox6))
                                .addGroup(jPanel4Layout.createSequentialGroup()
                                    .addComponent(jSpinner6, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jSpinner5, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGap(5, 5, 5)
                            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jSpinner8, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jCheckBox7))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jSpinner7, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jCheckBox8)))))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton2)
                    .addComponent(jButton1))
                .addContainerGap(29, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("ITEMS", jPanel4);

        jPanel2.setBackground(new java.awt.Color(0, 0, 120));

        jTable1.setFont(new java.awt.Font("Nunito Sans", 0, 12)); // NOI18N
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Item", "Price", "Quantity", "Total"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jLabel3.setFont(new java.awt.Font("Nunito Sans", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 200, 0));
        jLabel3.setText("Sub Total");

        jTextField1.setFont(new java.awt.Font("Nunito Sans", 0, 14)); // NOI18N

        jTextField2.setFont(new java.awt.Font("Nunito Sans", 0, 14)); // NOI18N

        jLabel4.setFont(new java.awt.Font("Nunito Sans", 0, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 200, 0));
        jLabel4.setText("Payment");

        jLabel5.setFont(new java.awt.Font("Nunito Sans", 0, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 200, 0));
        jLabel5.setText("Balance");

        jTextField3.setFont(new java.awt.Font("Nunito Sans", 0, 14)); // NOI18N

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(42, 42, 42)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(47, 47, 47)
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 33, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 350, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );

        jTabbedPane1.addTab("WAREHOUSE", jPanel2);

        jLabel2.setFont(new java.awt.Font("Nunito Sans", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(200, 0, 0));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("CLOSE");
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(105, 105, 105)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 688, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 862, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(70, 70, 70))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(38, 38, 38))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 444, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(34, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
              int sum = 0;
        int price;
        int qty;
        int total = 0;

        if (jCheckBox1.isSelected()) {
            String wiper = jCheckBox1.getText();
            price = 100;
            qty = Integer.parseInt(jSpinner1.getValue().toString());
            total = price * qty;
            model = (DefaultTableModel)jTable1.getModel();

            model.addRow(new Object[]
                {

                    wiper,
                    price,
                    qty,
                    total

                });
            }
        
        if (jCheckBox2.isSelected()) {
            String steering = jCheckBox2.getText();
            price = 29800;
            qty = Integer.parseInt(jSpinner2.getValue().toString());
            total = price * qty;
            model = (DefaultTableModel)jTable1.getModel();

            model.addRow(new Object[]
                {

                    steering,
                    price,
                    qty,
                    total

                });
            }

                
        if (jCheckBox3.isSelected()) {
            String washer = jCheckBox3.getText();
            price = 45;
            qty = Integer.parseInt(jSpinner3.getValue().toString());
            total = price * qty;
            model = (DefaultTableModel)jTable1.getModel();

            model.addRow(new Object[]
                {

                    washer,
                    price,
                    qty,
                    total

                });
            }
        
        
                
        if (jCheckBox4.isSelected()) {
            String filter = jCheckBox4.getText();
            price = 40;
            qty = Integer.parseInt(jSpinner4.getValue().toString());
            total = price * qty;
            model = (DefaultTableModel)jTable1.getModel();

            model.addRow(new Object[]
                {

                    filter,
                    price,
                    qty,
                    total

                });
            }
        
        if (jCheckBox5.isSelected()) {
            String battery = jCheckBox5.getText();
            price = 6000;
            qty = Integer.parseInt(jSpinner5.getValue().toString());
            total = price * qty;
            model = (DefaultTableModel)jTable1.getModel();

            model.addRow(new Object[]
                {

                    battery,
                    price,
                    qty,
                    total

                });
            }
        
                
        if (jCheckBox6.isSelected()) {
            String distributor = jCheckBox6.getText();
            price = 700000;
            qty = Integer.parseInt(jSpinner6.getValue().toString());
            total = price * qty;
            model = (DefaultTableModel)jTable1.getModel();

            model.addRow(new Object[]
                {

                    distributor,
                    price,
                    qty,
                    total

                });
            }
        
                
        if (jCheckBox7.isSelected()) {
            String radiator = jCheckBox7.getText();
            price = 1500;
            qty = Integer.parseInt(jSpinner7.getValue().toString());
            total = price * qty;
            model = (DefaultTableModel)jTable1.getModel();

            model.addRow(new Object[]
                {

                    radiator,
                    price,
                    qty,
                    total

                });
            }
        
                
        if (jCheckBox8.isSelected()) {
            String alternator = jCheckBox8.getText();
            price = 500000;
            qty = Integer.parseInt(jSpinner8.getValue().toString());
            total = price * qty;
            model = (DefaultTableModel)jTable1.getModel();

            model.addRow(new Object[]
                {

                    alternator,
                    price,
                    qty,
                    total

                });
            }
        
                
        if (jCheckBox9.isSelected()) {
            String oilfilter = jCheckBox9.getText();
            price = 345;
            qty = Integer.parseInt(jSpinner9.getValue().toString());
            total = price * qty;
            model = (DefaultTableModel)jTable1.getModel();

            model.addRow(new Object[]
                {

                    oilfilter,
                    price,
                    qty,
                    total

                });
            }
        
                
        if (jCheckBox10.isSelected()) {
            String diskbrake = jCheckBox10.getText();
            price = 300;
            qty = Integer.parseInt(jSpinner10.getValue().toString());
            total = price * qty;
            model = (DefaultTableModel)jTable1.getModel();

            model.addRow(new Object[]
                {

                    diskbrake,
                    price,
                    qty,
                    total

                });
            }
        
                
        if (jCheckBox11.isSelected()) {
            String transmission = jCheckBox11.getText();
            price = 760000;
            qty = Integer.parseInt(jSpinner11.getValue().toString());
            total = price * qty;
            model = (DefaultTableModel)jTable1.getModel();

            model.addRow(new Object[]
                {

                    transmission,
                    price,
                    qty,
                    total

                });
            }
        
                
        if (jCheckBox12.isSelected()) {
            String muffler = jCheckBox12.getText();
            price = 999;
            qty = Integer.parseInt(jSpinner12.getValue().toString());
            total = price * qty;
            model = (DefaultTableModel)jTable1.getModel();

            model.addRow(new Object[]
                {

                    muffler,
                    price,
                    qty,
                    total

                });
            }
        
                
        if (jCheckBox13.isSelected()) {
            String shaft = jCheckBox13.getText();
            price = 1422888;
            qty = Integer.parseInt(jSpinner13.getValue().toString());
            total = price * qty;
            model = (DefaultTableModel)jTable1.getModel();

            model.addRow(new Object[]
                {

                    shaft,
                    price,
                    qty,
                    total

                });
            }
        
               
        if (jCheckBox14.isSelected()) {
            String wheel = jCheckBox14.getText();
            price = 360000;
            qty = Integer.parseInt(jSpinner14.getValue().toString());
            total = price * qty;
            model = (DefaultTableModel)jTable1.getModel();

            model.addRow(new Object[]
                {

                    wheel,
                    price,
                    qty,
                    total

                });
            }
        
                if (jCheckBox15.isSelected()) {
            String light = jCheckBox15.getText();
            price = 9000;
            qty = Integer.parseInt(jSpinner15.getValue().toString());
            total = price * qty;
            model = (DefaultTableModel)jTable1.getModel();

            model.addRow(new Object[]
                {

                    light,
                    price,
                    qty,
                    total

                });
            } 
                
              if (jCheckBox16.isSelected()) {
            String trunk = jCheckBox16.getText();
            price = 20000;
            qty = Integer.parseInt(jSpinner16.getValue().toString());
            total = price * qty;
            model = (DefaultTableModel)jTable1.getModel();

            model.addRow(new Object[]
                {

                    trunk,
                    price,
                    qty,
                    total

                });
            } 
        
        for (int i=0; i < jTable1.getRowCount(); i++)
        {
            sum = sum + Integer.parseInt(jTable1.getValueAt(i, 3).toString());
        }
        
        jTextField1.setText(Integer.toString(sum));
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
               int subtotal, payment, balance;
            subtotal = Integer.parseInt(jTextField1.getText());
            payment = Integer.parseInt(jTextField2.getText());
            balance = payment - subtotal;
            jTextField3.setText(String.valueOf(balance));
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseClicked
        System.exit(0);
    }//GEN-LAST:event_jLabel2MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Main().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JCheckBox jCheckBox10;
    private javax.swing.JCheckBox jCheckBox11;
    private javax.swing.JCheckBox jCheckBox12;
    private javax.swing.JCheckBox jCheckBox13;
    private javax.swing.JCheckBox jCheckBox14;
    private javax.swing.JCheckBox jCheckBox15;
    private javax.swing.JCheckBox jCheckBox16;
    private javax.swing.JCheckBox jCheckBox2;
    private javax.swing.JCheckBox jCheckBox3;
    private javax.swing.JCheckBox jCheckBox4;
    private javax.swing.JCheckBox jCheckBox5;
    private javax.swing.JCheckBox jCheckBox6;
    private javax.swing.JCheckBox jCheckBox7;
    private javax.swing.JCheckBox jCheckBox8;
    private javax.swing.JCheckBox jCheckBox9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSpinner jSpinner1;
    private javax.swing.JSpinner jSpinner10;
    private javax.swing.JSpinner jSpinner11;
    private javax.swing.JSpinner jSpinner12;
    private javax.swing.JSpinner jSpinner13;
    private javax.swing.JSpinner jSpinner14;
    private javax.swing.JSpinner jSpinner15;
    private javax.swing.JSpinner jSpinner16;
    private javax.swing.JSpinner jSpinner2;
    private javax.swing.JSpinner jSpinner3;
    private javax.swing.JSpinner jSpinner4;
    private javax.swing.JSpinner jSpinner5;
    private javax.swing.JSpinner jSpinner6;
    private javax.swing.JSpinner jSpinner7;
    private javax.swing.JSpinner jSpinner8;
    private javax.swing.JSpinner jSpinner9;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    // End of variables declaration//GEN-END:variables
}
