/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package bread.store.inventory;

import javax.swing.table.DefaultTableModel;

/**
 *
 * @author bajal
 */
public class Bread extends javax.swing.JFrame {

    /**
     * Creates new form Bread
     */
    public Bread() {
        initComponents();
    }

    DefaultTableModel model = new DefaultTableModel();
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        jCheckBox1 = new javax.swing.JCheckBox();
        jCheckBox2 = new javax.swing.JCheckBox();
        jCheckBox3 = new javax.swing.JCheckBox();
        jCheckBox4 = new javax.swing.JCheckBox();
        jCheckBox5 = new javax.swing.JCheckBox();
        jCheckBox6 = new javax.swing.JCheckBox();
        jCheckBox7 = new javax.swing.JCheckBox();
        jCheckBox8 = new javax.swing.JCheckBox();
        jCheckBox9 = new javax.swing.JCheckBox();
        jCheckBox10 = new javax.swing.JCheckBox();
        jCheckBox11 = new javax.swing.JCheckBox();
        jCheckBox12 = new javax.swing.JCheckBox();
        jCheckBox13 = new javax.swing.JCheckBox();
        jCheckBox14 = new javax.swing.JCheckBox();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jSpinner1 = new javax.swing.JSpinner();
        jSpinner2 = new javax.swing.JSpinner();
        jSpinner3 = new javax.swing.JSpinner();
        jSpinner4 = new javax.swing.JSpinner();
        jSpinner5 = new javax.swing.JSpinner();
        jSpinner6 = new javax.swing.JSpinner();
        jSpinner7 = new javax.swing.JSpinner();
        jSpinner8 = new javax.swing.JSpinner();
        jSpinner9 = new javax.swing.JSpinner();
        jSpinner10 = new javax.swing.JSpinner();
        jSpinner11 = new javax.swing.JSpinner();
        jSpinner12 = new javax.swing.JSpinner();
        jSpinner13 = new javax.swing.JSpinner();
        jSpinner14 = new javax.swing.JSpinner();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(200, 0, 0));

        jPanel1.setBackground(new java.awt.Color(200, 0, 0));

        jLabel1.setFont(new java.awt.Font("Nunito Sans", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 225, 0));
        jLabel1.setText("BREAD STORE");

        jTabbedPane1.setBackground(new java.awt.Color(200, 0, 0));
        jTabbedPane1.setFont(new java.awt.Font("Nunito Sans", 1, 14)); // NOI18N

        jPanel2.setBackground(new java.awt.Color(200, 0, 0));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jCheckBox1.setBackground(new java.awt.Color(200, 0, 0));
        jCheckBox1.setFont(new java.awt.Font("Nunito Sans", 1, 12)); // NOI18N
        jCheckBox1.setForeground(new java.awt.Color(255, 225, 0));
        jCheckBox1.setText("Carrot Cake");
        jPanel2.add(jCheckBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 40, -1, -1));

        jCheckBox2.setBackground(new java.awt.Color(200, 0, 0));
        jCheckBox2.setFont(new java.awt.Font("Nunito Sans", 1, 12)); // NOI18N
        jCheckBox2.setForeground(new java.awt.Color(255, 225, 0));
        jCheckBox2.setText("Banana Bread");
        jPanel2.add(jCheckBox2, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 90, -1, -1));

        jCheckBox3.setBackground(new java.awt.Color(200, 0, 0));
        jCheckBox3.setFont(new java.awt.Font("Nunito Sans", 1, 12)); // NOI18N
        jCheckBox3.setForeground(new java.awt.Color(255, 225, 0));
        jCheckBox3.setText("Pudding");
        jPanel2.add(jCheckBox3, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 170, -1, -1));

        jCheckBox4.setBackground(new java.awt.Color(200, 0, 0));
        jCheckBox4.setFont(new java.awt.Font("Nunito Sans", 1, 12)); // NOI18N
        jCheckBox4.setForeground(new java.awt.Color(255, 225, 0));
        jCheckBox4.setText("Brownies");
        jPanel2.add(jCheckBox4, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 130, -1, -1));

        jCheckBox5.setBackground(new java.awt.Color(200, 0, 0));
        jCheckBox5.setFont(new java.awt.Font("Nunito Sans", 1, 12)); // NOI18N
        jCheckBox5.setForeground(new java.awt.Color(255, 225, 0));
        jCheckBox5.setText("Sponge Cake");
        jPanel2.add(jCheckBox5, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 220, -1, -1));

        jCheckBox6.setBackground(new java.awt.Color(200, 0, 0));
        jCheckBox6.setFont(new java.awt.Font("Nunito Sans", 1, 12)); // NOI18N
        jCheckBox6.setForeground(new java.awt.Color(255, 225, 0));
        jCheckBox6.setText("Lemon Tart");
        jPanel2.add(jCheckBox6, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 260, 101, -1));

        jCheckBox7.setBackground(new java.awt.Color(200, 0, 0));
        jCheckBox7.setFont(new java.awt.Font("Nunito Sans", 1, 12)); // NOI18N
        jCheckBox7.setForeground(new java.awt.Color(255, 225, 0));
        jCheckBox7.setText("Cassava Cake");
        jPanel2.add(jCheckBox7, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 310, -1, -1));

        jCheckBox8.setBackground(new java.awt.Color(200, 0, 0));
        jCheckBox8.setFont(new java.awt.Font("Nunito Sans", 1, 12)); // NOI18N
        jCheckBox8.setForeground(new java.awt.Color(255, 225, 0));
        jCheckBox8.setText("Crinkles");
        jPanel2.add(jCheckBox8, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 350, -1, -1));

        jCheckBox9.setBackground(new java.awt.Color(200, 0, 0));
        jCheckBox9.setFont(new java.awt.Font("Nunito Sans", 1, 12)); // NOI18N
        jCheckBox9.setForeground(new java.awt.Color(255, 225, 0));
        jCheckBox9.setText("Sugar Cookies");
        jPanel2.add(jCheckBox9, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 40, -1, -1));

        jCheckBox10.setBackground(new java.awt.Color(200, 0, 0));
        jCheckBox10.setFont(new java.awt.Font("Nunito Sans", 1, 12)); // NOI18N
        jCheckBox10.setForeground(new java.awt.Color(255, 225, 0));
        jCheckBox10.setText("Fruit Cake");
        jPanel2.add(jCheckBox10, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 90, -1, -1));

        jCheckBox11.setBackground(new java.awt.Color(200, 0, 0));
        jCheckBox11.setFont(new java.awt.Font("Nunito Sans", 1, 12)); // NOI18N
        jCheckBox11.setForeground(new java.awt.Color(255, 225, 0));
        jCheckBox11.setText("Apple Pie");
        jPanel2.add(jCheckBox11, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 130, 83, -1));

        jCheckBox12.setBackground(new java.awt.Color(200, 0, 0));
        jCheckBox12.setFont(new java.awt.Font("Nunito Sans", 1, 12)); // NOI18N
        jCheckBox12.setForeground(new java.awt.Color(255, 225, 0));
        jCheckBox12.setText("<html>Chocolate Chip<br>Cookies");
        jPanel2.add(jCheckBox12, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 170, -1, -1));

        jCheckBox13.setBackground(new java.awt.Color(200, 0, 0));
        jCheckBox13.setFont(new java.awt.Font("Nunito Sans", 1, 12)); // NOI18N
        jCheckBox13.setForeground(new java.awt.Color(255, 225, 0));
        jCheckBox13.setText("Oatmeal Bars");
        jPanel2.add(jCheckBox13, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 220, -1, -1));

        jCheckBox14.setBackground(new java.awt.Color(200, 0, 0));
        jCheckBox14.setFont(new java.awt.Font("Nunito Sans", 1, 12)); // NOI18N
        jCheckBox14.setForeground(new java.awt.Color(255, 225, 0));
        jCheckBox14.setText("Blueberry Muffins");
        jPanel2.add(jCheckBox14, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 260, -1, -1));

        jButton1.setFont(new java.awt.Font("Nunito Sans", 1, 14)); // NOI18N
        jButton1.setText("ADD TO LIST");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 310, 180, -1));

        jButton2.setFont(new java.awt.Font("Nunito Sans", 1, 14)); // NOI18N
        jButton2.setText("PRINT");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 350, 180, -1));

        jSpinner1.setFont(new java.awt.Font("Nunito Sans", 0, 12)); // NOI18N
        jPanel2.add(jSpinner1, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 40, 58, 27));

        jSpinner2.setFont(new java.awt.Font("Nunito Sans", 0, 12)); // NOI18N
        jPanel2.add(jSpinner2, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 90, 58, 27));

        jSpinner3.setFont(new java.awt.Font("Nunito Sans", 0, 12)); // NOI18N
        jPanel2.add(jSpinner3, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 130, 58, 27));

        jSpinner4.setFont(new java.awt.Font("Nunito Sans", 0, 12)); // NOI18N
        jPanel2.add(jSpinner4, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 170, 58, 27));

        jSpinner5.setFont(new java.awt.Font("Nunito Sans", 0, 12)); // NOI18N
        jPanel2.add(jSpinner5, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 220, 58, 27));

        jSpinner6.setFont(new java.awt.Font("Nunito Sans", 0, 12)); // NOI18N
        jPanel2.add(jSpinner6, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 260, 58, 27));

        jSpinner7.setFont(new java.awt.Font("Nunito Sans", 0, 12)); // NOI18N
        jPanel2.add(jSpinner7, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 310, 58, 27));

        jSpinner8.setFont(new java.awt.Font("Nunito Sans", 0, 12)); // NOI18N
        jPanel2.add(jSpinner8, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 350, 58, 27));

        jSpinner9.setFont(new java.awt.Font("Nunito Sans", 0, 12)); // NOI18N
        jPanel2.add(jSpinner9, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 40, 58, 27));

        jSpinner10.setFont(new java.awt.Font("Nunito Sans", 0, 12)); // NOI18N
        jPanel2.add(jSpinner10, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 90, 58, 27));

        jSpinner11.setFont(new java.awt.Font("Nunito Sans", 0, 12)); // NOI18N
        jPanel2.add(jSpinner11, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 130, 58, 27));

        jSpinner12.setFont(new java.awt.Font("Nunito Sans", 0, 12)); // NOI18N
        jPanel2.add(jSpinner12, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 180, 58, 27));

        jSpinner13.setFont(new java.awt.Font("Nunito Sans", 0, 12)); // NOI18N
        jPanel2.add(jSpinner13, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 220, 58, 27));

        jSpinner14.setFont(new java.awt.Font("Nunito Sans", 0, 12)); // NOI18N
        jPanel2.add(jSpinner14, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 260, 58, 27));

        jTabbedPane1.addTab("LIST OF PRODUCTS", jPanel2);

        jPanel3.setBackground(new java.awt.Color(200, 0, 0));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Product Name", "Price", "Quantity", "Total"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jLabel2.setFont(new java.awt.Font("Nunito Sans", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 225, 0));
        jLabel2.setText("SUB TOTAL");

        jTextField1.setFont(new java.awt.Font("Nunito Sans", 0, 14)); // NOI18N

        jLabel3.setFont(new java.awt.Font("Nunito Sans", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 225, 0));
        jLabel3.setText("PAYMENT");

        jTextField2.setFont(new java.awt.Font("Nunito Sans", 0, 14)); // NOI18N

        jLabel4.setFont(new java.awt.Font("Nunito Sans", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 225, 0));
        jLabel4.setText("BALANCE");

        jTextField3.setFont(new java.awt.Font("Nunito Sans", 0, 14)); // NOI18N

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(22, 22, 22))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 359, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jTabbedPane1.addTab("TABLE OF PURCHASED PRODUCTS", jPanel3);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 258, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 586, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(25, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 452, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(25, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
      int sum = 0;
        int price;
        int qty;
        int total = 0;

        if (jCheckBox1.isSelected()) {
            String carrot = jCheckBox1.getText();
            price = 20;
            qty = Integer.parseInt(jSpinner1.getValue().toString());
            total = price * qty;
            model = (DefaultTableModel)jTable1.getModel();

            model.addRow(new Object[]
                {

                    carrot,
                    price,
                    qty,
                    total

                });
            }
        
        if (jCheckBox2.isSelected()) {
            String banana = jCheckBox2.getText();
            price = 30;
            qty = Integer.parseInt(jSpinner2.getValue().toString());
            total = price * qty;
            model = (DefaultTableModel)jTable1.getModel();

            model.addRow(new Object[]
                {

                    banana,
                    price,
                    qty,
                    total

                });
            }

                
        if (jCheckBox3.isSelected()) {
            String brownies = jCheckBox3.getText();
            price = 30;
            qty = Integer.parseInt(jSpinner3.getValue().toString());
            total = price * qty;
            model = (DefaultTableModel)jTable1.getModel();

            model.addRow(new Object[]
                {

                    brownies,
                    price,
                    qty,
                    total

                });
            }
        
        
                
        if (jCheckBox4.isSelected()) {
            String pudding = jCheckBox4.getText();
            price = 25;
            qty = Integer.parseInt(jSpinner4.getValue().toString());
            total = price * qty;
            model = (DefaultTableModel)jTable1.getModel();

            model.addRow(new Object[]
                {

                    pudding,
                    price,
                    qty,
                    total

                });
            }
        
        if (jCheckBox5.isSelected()) {
            String scake = jCheckBox5.getText();
            price = 25;
            qty = Integer.parseInt(jSpinner5.getValue().toString());
            total = price * qty;
            model = (DefaultTableModel)jTable1.getModel();

            model.addRow(new Object[]
                {

                    scake,
                    price,
                    qty,
                    total

                });
            }
        
                
        if (jCheckBox6.isSelected()) {
            String lemont = jCheckBox6.getText();
            price = 25;
            qty = Integer.parseInt(jSpinner6.getValue().toString());
            total = price * qty;
            model = (DefaultTableModel)jTable1.getModel();

            model.addRow(new Object[]
                {

                    lemont,
                    price,
                    qty,
                    total

                });
            }
        
                
        if (jCheckBox7.isSelected()) {
            String cassava = jCheckBox7.getText();
            price = 30;
            qty = Integer.parseInt(jSpinner7.getValue().toString());
            total = price * qty;
            model = (DefaultTableModel)jTable1.getModel();

            model.addRow(new Object[]
                {

                    cassava,
                    price,
                    qty,
                    total

                });
            }
        
                
        if (jCheckBox8.isSelected()) {
            String crinkles = jCheckBox8.getText();
            price = 10;
            qty = Integer.parseInt(jSpinner8.getValue().toString());
            total = price * qty;
            model = (DefaultTableModel)jTable1.getModel();

            model.addRow(new Object[]
                {

                    crinkles,
                    price,
                    qty,
                    total

                });
            }
        
                
        if (jCheckBox9.isSelected()) {
            String scookies = jCheckBox9.getText();
            price = 10;
            qty = Integer.parseInt(jSpinner9.getValue().toString());
            total = price * qty;
            model = (DefaultTableModel)jTable1.getModel();

            model.addRow(new Object[]
                {

                    scookies,
                    price,
                    qty,
                    total

                });
            }
        
                
        if (jCheckBox10.isSelected()) {
            String fcake = jCheckBox10.getText();
            price = 40;
            qty = Integer.parseInt(jSpinner10.getValue().toString());
            total = price * qty;
            model = (DefaultTableModel)jTable1.getModel();

            model.addRow(new Object[]
                {

                    fcake,
                    price,
                    qty,
                    total

                });
            }
        
                
        if (jCheckBox11.isSelected()) {
            String appie = jCheckBox11.getText();
            price = 25;
            qty = Integer.parseInt(jSpinner11.getValue().toString());
            total = price * qty;
            model = (DefaultTableModel)jTable1.getModel();

            model.addRow(new Object[]
                {

                    appie,
                    price,
                    qty,
                    total

                });
            }
        
                
        if (jCheckBox12.isSelected()) {
            String ccc = jCheckBox12.getText();
            price = 5;
            qty = Integer.parseInt(jSpinner12.getValue().toString());
            total = price * qty;
            model = (DefaultTableModel)jTable1.getModel();

            model.addRow(new Object[]
                {

                    ccc,
                    price,
                    qty,
                    total

                });
            }
        
                
        if (jCheckBox13.isSelected()) {
            String oatbars = jCheckBox13.getText();
            price = 10;
            qty = Integer.parseInt(jSpinner13.getValue().toString());
            total = price * qty;
            model = (DefaultTableModel)jTable1.getModel();

            model.addRow(new Object[]
                {

                    oatbars,
                    price,
                    qty,
                    total

                });
            }
        
               
        if (jCheckBox14.isSelected()) {
            String bbmuffins = jCheckBox14.getText();
            price = 15;
            qty = Integer.parseInt(jSpinner14.getValue().toString());
            total = price * qty;
            model = (DefaultTableModel)jTable1.getModel();

            model.addRow(new Object[]
                {

                    bbmuffins,
                    price,
                    qty,
                    total

                });
            }
        
        for (int i=0; i < jTable1.getRowCount(); i++)
        {
            sum = sum + Integer.parseInt(jTable1.getValueAt(i, 3).toString());
        }
        
        jTextField1.setText(Integer.toString(sum));
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        int subtotal, payment, balance;
            subtotal = Integer.parseInt(jTextField1.getText());
            payment = Integer.parseInt(jTextField2.getText());
            balance = payment - subtotal;
            jTextField3.setText(String.valueOf(balance));
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Bread.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Bread.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Bread.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Bread.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Bread().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JCheckBox jCheckBox10;
    private javax.swing.JCheckBox jCheckBox11;
    private javax.swing.JCheckBox jCheckBox12;
    private javax.swing.JCheckBox jCheckBox13;
    private javax.swing.JCheckBox jCheckBox14;
    private javax.swing.JCheckBox jCheckBox2;
    private javax.swing.JCheckBox jCheckBox3;
    private javax.swing.JCheckBox jCheckBox4;
    private javax.swing.JCheckBox jCheckBox5;
    private javax.swing.JCheckBox jCheckBox6;
    private javax.swing.JCheckBox jCheckBox7;
    private javax.swing.JCheckBox jCheckBox8;
    private javax.swing.JCheckBox jCheckBox9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSpinner jSpinner1;
    private javax.swing.JSpinner jSpinner10;
    private javax.swing.JSpinner jSpinner11;
    private javax.swing.JSpinner jSpinner12;
    private javax.swing.JSpinner jSpinner13;
    private javax.swing.JSpinner jSpinner14;
    private javax.swing.JSpinner jSpinner2;
    private javax.swing.JSpinner jSpinner3;
    private javax.swing.JSpinner jSpinner4;
    private javax.swing.JSpinner jSpinner5;
    private javax.swing.JSpinner jSpinner6;
    private javax.swing.JSpinner jSpinner7;
    private javax.swing.JSpinner jSpinner8;
    private javax.swing.JSpinner jSpinner9;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    // End of variables declaration//GEN-END:variables
}
